{
 "title": "Sonar",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "example_com_time_ms_bucket (example.com)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(example_com_time_ms_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(example_com_time_ms_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(www_example_com_time_ms_count[$__interval]))"
    }
   ]
  },
  {
   "title": "Success Ratio",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "(sum(rate(www_example_com_success[$__interval])) * 100) / sum(rate(www_example_com_time_ms_count[$__interval]))",
     "legendFormat": "Success / Failure Ratio"
    }
   ]
  }
 ]
}